require("zaplachi.set")
require("zaplachi.remap")
require("zaplachi.packer")
require("zaplachi.color")
require("zaplachi.lsp")
require("zaplachi.treesitter")
require("zaplachi.telescope")
require("zaplachi.autocomplete")
require("zaplachi.comment")
require("zaplachi.toggleterm")
require("zaplachi.airline")
require("zaplachi.whichkey")
--require("zaplachi.packages")

