require("zaplachi.packages.lsp")
require("zaplachi.packages.autocomplete")
require("zaplachi.packages.treesitter")
require("zaplachi.packages.telescope")
require("zaplachi.packages.comment")
require("zaplachi.packages.color")
require("zaplachi.packages.toggleterm")
require("zaplachi.packages.whichkey")
require("zaplachi.packages.airline")

